version: '3.8'

services:
  bot:
    build: .
    container_name: socreveto1989-bot-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris  # <--- Ajoute cette ligne ici